### PR TITLE
Updated the pom and its dependencies for Spring etc. 

### PR DESCRIPTION
**Pull request by chasegawa**
Reference: https://github.com/spring-projects/spring-framework/wiki/Migrating-from-earlier-versions-of-the-spring-framework

Did not update:
* ehcache (from resource-server-utils)
* groovy (from cernunnous)

Update the pom and dependencies for Spring. Impacted code was updated to match changes in package references as needed. Now at the following revisions:

Spring to 4.1.4
Junit to 4.12
Servlet-api to 3.0.1
httpclient to 4.4
jackson to 2.3.0
xerces to 2.11.0
javassist to 3.12.1.GA
hibernate to 3.6.10.Final
slf4j to 1.7.10
rome to 1.5.0
compiler (java) to 1.7

### CODE REVIEW

**Comment by jameswennmacher** [comment]
Hold off on merging this until cernunnos is updated.

When the Newsreader portlet was upgraded to Spring 4.1.4, an ant initdb fails because Spring removed a deprecated class.

http://docs.spring.io/spring/docs/3.2.13.RELEASE/javadoc-api/org/springframework/util/ClassUtils.html#forName(java.lang.String)
was deprecated in Spring 3.0 and removed in 4.0

http://docs.spring.io/spring/docs/3.2.13.RELEASE/javadoc-api/org/springframework/util/ClassUtils.html#forName(java.lang.String,%20java.lang.ClassLoader)
replaces it.  You can pass in null for the 2nd parameter to get equivalent functionality to what was there.

The stack trace from the ant initdb was:

     [exec]      [java] **************************************************
     [exec]      [java] ** Invoking ScriptRunner.run(Task, TaskRequest)
     [exec]      [java] ** TaskRequest contains 4 elements
     [exec]      [java] **   - $1=/home/jwennmacher/projects/uPortal/uportal-portlets-overlay/NewsReaderPortlet/src/main/data
     [exec]      [java] **   - $2=/home/jwennmacher/projects/uPortal/uportal-portlets-overlay/NewsReaderPortlet/target/NewsReaderPortlet/WEB-INF/context/importExportContext.xml
     [exec]      [java] **   - Attributes.CACHE={}
     [exec]      [java] **   - Attributes.ORIGIN=classpath://org/jasig/portlet/newsreader/io/import.crn.xml
     [exec]      [java] **************************************************
     [exec]      [java]
     [exec]      [java] Exception in thread "main" org.danann.cernunnos.ManagedException: The Cernunnos Runtime encountered an error:
     [exec]      [java]         Origin Document:  classpath://org/jasig/portlet/newsreader/io/import.crn.xml
     [exec]      [java]         Source:  /with/attribute[4]/text()
     [exec]      [java]         Entity Name:  ${groovy}
     [exec]      [java]     at org.danann.cernunnos.runtime.RuntimePhraseDecorator.evaluate(RuntimePhraseDecorator.java:103)
     [exec]      [java]     at org.danann.cernunnos.runtime.ConcatenatingPhrase.evaluate(ConcatenatingPhrase.java:77)
     [exec]      [java]     at org.danann.cernunnos.core.WithTask.perform(WithTask.java:86)
     [exec]      [java]     at org.danann.cernunnos.runtime.RuntimeTaskDecorator.perform(RuntimeTaskDecorator.java:77)
     [exec]      [java]     at org.danann.cernunnos.runtime.ScriptRunner$TaskDecorator.perform(ScriptRunner.java:435)
     [exec]      [java]     at org.danann.cernunnos.runtime.ScriptRunner.run(ScriptRunner.java:287)
     [exec]      [java]     at org.danann.cernunnos.runtime.ScriptRunner.run(ScriptRunner.java:224)
     [exec]      [java]     at org.danann.cernunnos.runtime.ScriptRunner.run(ScriptRunner.java:157)
     [exec]      [java]     at org.danann.cernunnos.runtime.Main.main(Main.java:103)
     [exec]      [java] Caused by: java.lang.NoSuchMethodError: org.springframework.util.ClassUtils.forName(Ljava/lang/String;)Ljava/lang/Class;
     [exec]      [java]     at org.danann.cernunnos.script.ScriptEvaluator.<clinit>(ScriptEvaluator.java:45)
     [exec]      [java]     at org.danann.cernunnos.script.ScriptEvaluatorFactory.createObject(ScriptEvaluatorFactory.java:31)
     [exec]      [java]     at org.danann.cernunnos.script.ScriptEvaluatorFactory.createObject(ScriptEvaluatorFactory.java:18)
     [exec]      [java]     at org.danann.cernunnos.DynamicCacheHelper.getCachedObject(DynamicCacheHelper.java:116)
     [exec]      [java]     at org.danann.cernunnos.script.ScriptPhrase.evaluate(ScriptPhrase.java:73)
     [exec]      [java]     at org.danann.cernunnos.runtime.RuntimePhraseDecorator.evaluate(RuntimePhraseDecorator.java:75)
     [exec]      [java]     ... 8 more

**Comment by groybal** [comment]
Cernunnos 1.3.0, with the required update, has been released.
http://search.maven.org/#search%7Cga%7C1%7Ccernunnos

**Comment by drewwills** [comment]
Nice work guys.  I'll be looking to incorporate these updates shortly.

**Comment by jameswennmacher** [comment]
I see ehcache from parent is v2.6.5 which is fine.

**Comment by drewwills** [comment]
Merged out-of-band w/ some conflict resolution.

**Pull request closed without merging**
